# Generated by Django 3.2.8 on 2021-10-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('Product', models.CharField(max_length=500)),
                ('Quantity', models.IntegerField()),
                ('OrderSubtotal', models.FloatField()),
                ('OrderTotal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductStock', models.IntegerField()),
                ('ProductPrice', models.FloatField()),
            ],
        ),
    ]
